version: '3.8'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_DB: practica_herramientas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"  # Cambia el puerto local a 5433 para evitar conflictos
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practicas_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/practica_herramientas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: